---
Name: 'dd-canonical'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - DorsetDigital\SilverStripeCanonical\SiteTreeCanonicalExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - DorsetDigital\SilverstripeCanonical\ConfigCanonicalExtension
    